<?php
class RequestBinTest extends PHPUnit_Framework_TestCase {

    /**
     * @var \RemoteWebDriver
     */
    protected $webDriver;

    public function setUp()
    {
        $capabilities = array(\WebDriverCapabilityType::BROWSER_NAME => 'phantomjs');
        $this->webDriver = RemoteWebDriver::create('http://localhost:4444/wd/hub', $capabilities);
    }

    protected $url = 'http://127.0.0.1:80/';

    public function testRequests()
    {
        $this->webDriver->get($this->url);
        $this->assertContains('Request Bin', $this->webDriver->getTitle());

        $urlField = $this->webDriver->findElement(\WebDriverBy::id("capture-url"));
        $urlValue = $urlField->getAttribute("value");
        $this->webDriver->get($urlValue);

        $this->assertContains('captured', $this->webDriver->getPageSource());

        $this->webDriver->get($this->url);
        $this->assertContains('GET', $this->webDriver->getPageSource());
        $this->webDriver->findElement(\WebDriverBy::partialLinkText("View"))->click();

        $this->assertContains('PhantomJS', $this->webDriver->getPageSource());
        $this->assertContains('127.0.0.1', $this->webDriver->getPageSource());
        $this->assertContains('GET', $this->webDriver->getPageSource());
        $this->assertContains('capture', $this->webDriver->getPageSource());
    }


    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

}
